name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - 'com.tibia.Tibia.*'

  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - uses: crazy-max/ghaction-import-gpg@v6
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          manifest-path: com.tibia.Tibia.json
          gpg-sign: ${{ steps.import-gpg.outputs.keyid }}
          verbose: true
