name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - 'com.tibia.Tibia.*'

  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - uses: crazy-max/ghaction-import-gpg@v6
        id: import-gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: com.tibia.Tibia.json
          gpg-sign: ${{ steps.import-gpg.outputs.keyid }}

      - uses: flatpak/flatpak-github-actions/flat-manager@v6
        with:
          repository: ""
          flat-manager-url: https://tibiapak.rsa.sh
          token: ${{ secrets.REPO_TOKEN }}
